apiVersion: v1
kind: Service
metadata:
  name: redis-node-redouane-service
spec:
  selector:
    app: node-redis-redouane
  ports:
    - port: 5000
      targetPort: 5000
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: redis-redouane-service
spec:
  selector:
    app: redis-redouane
  ports:
    - port: 6379
      targetPort: 6379
  type: LoadBalancer